version: '3.9'

services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: finance_db
  finance-service:
    image: smartfinance
    build: backend
    ports:
      - '8080:8080'
    depends_on:
      - db
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/finance_db
  bot-client:
    image: bot-client:latest
    build: botClient
    ports:
      - "8086:8086"
    depends_on:
      - rabbitmq
    environment:
      FINANCE_HERO_TG_BOT_TOKEN: ${FINANCE_HERO_TG_BOT_TOKEN}
  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "5672:5672"       # стандартный порт RabbitMQ
      - "15672:15672"     # порт для панели управления RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}