app:
  telegram-token: ${TELEGRAM_TOKEN}

server:
  port: 8090

spring:
  application:
    name: bot
  config:
    import: optional:file:.env[.properties]

springdoc:
  swagger-ui:
    path: /swagger-ui